One-liner setup from github is back

diff --git a/adblock b/adblock
--- a/adblock
+++ b/adblock
@@ -1,5 +1,5 @@
 #!/bin/sh /etc/rc.common
-# adblock init-script utilizing procd version 3.1.0 by stangri based on bole5's script.
+# adblock init-script utilizing procd version 3.2.0 by stangri based on bole5's script.
 
 START=99
 USE_PROCD=1
@@ -16,8 +16,7 @@ logmsg=''
 
 [ -s /bin/uclient-fetch ] && CLIENT='/bin/uclient-fetch' || CLIENT='/usr/bin/wget'
 
-output()
-{
+output () {
     local level
     [ $# -eq 2 ] && level=$2 || level=1
 	[ $verbosity -lt $level ] && return 0
@@ -25,28 +24,31 @@ output()
 	[ $(echo -e -n $1 | wc -l) -gt 0 ] && logger -t "adblock[$$]" "$(echo -e -n ${logmsg}${1})" && logmsg='' || logmsg=${logmsg}${1}
 }
 
-update()
-{
-    echo -e -n 'Updating /etc/init.d/adblock script... '
-    $CLIENT --no-check-certificate -qO /etc/init.d/adblock.new https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/adblock && mv /etc/init.d/adblock.new /etc/init.d/adblock && chmod +x /etc/init.d/adblock && echo -e -n  'Done!\n' || echo -e -n 'FAIL!\n' 
+update () {
+    echo -e -n '/etc/init.d/adblock script update... '
+    $CLIENT --no-check-certificate -qO /etc/init.d/adblock.new https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/adblock && mv /etc/init.d/adblock.new /etc/init.d/adblock && chmod +x /etc/init.d/adblock && echo -e -n  '[OK]\n' && return 0 || ( echo -e -n '[FAIL]\n' && return 1 )
 }
 
-setup()
-{
+setup () {
     local pixelservip=198.18.0.1
     local pixelservipv6='::ffff:c612:0001'
-    echo 'Setting up Packages'
+
+	update
+	[ $? -ne 0 ] && echo "Failed to fetch AdBlock script from github, check if wget/libopenssl or uclient-fetch/libustream-mbedtls are installed." && exit -1
+
+    echo -e -n 'Packages setup... '
     opkg update  >/dev/null  2>&1
-    opkg install uhttpd coreutils-sort >/dev/null 2>&1
+    opkg install coreutils-sort >/dev/null 2>&1
     
     if [ -s /bin/uclient-fetch ]; then
     	[ ! -s /lib/libustream-ssl.so ] && opkg install libustream-mbedtls >/dev/null 2>&1
     else
-    	opkg install wget libopenssl >/dev/null  2>&1
+    	opkg install wget libopenssl >/dev/null 2>&1
     fi
-
-    echo 'Setting up PixelServ'
-    if [ ! $(uci -q get uhttpd.adblockpixelserv.listen_http) ]; then
+	echo -e -n  '[OK]\n'
+    
+    echo -e -n 'PixelServ setup... '
+    if [ "$(uci -q get uhttpd.adblockpixelserv.listen_http)" = "" ]; then
 	    mkdir /www_adblock
 	    echo -ne 'GIF89a1010\x8000\xff\xff\xff000!\xf9\x0400000,000010100\x02\x02D10;' | tr 01 '\000\001' > /www_adblock/blank.gif
 	    uci add uhttpd uhttpd
@@ -66,7 +68,7 @@ setup()
 	    uci commit uhttpd
 	    /etc/init.d/uhttpd restart
     fi
-    if [ ! $(uci -q get uhttpd.adblockpixelservssl.listen_http) ]; then
+    if [ "$(uci -q get uhttpd.adblockpixelservssl.listen_http)" = "" ]; then
 	    mkdir /www_adblock
 	    echo -ne 'GIF89a1010\x8000\xff\xff\xff000!\xf9\x0400000,000010100\x02\x02D10;' | tr 01 '\000\001' > /www_adblock/blank.gif
 	    uci add uhttpd uhttpd
@@ -86,16 +88,18 @@ setup()
 	    uci commit uhttpd
 	    /etc/init.d/uhttpd restart
     fi
-
-    echo 'Setting up Firewall'
+	echo -e -n  '[OK]\n'
+    
+    echo -e -n 'Firewall setup... '
 #	sed -i '/192.168.3.254/d' /etc/firewall.user
     grep -q "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip --dport 80 -j REDIRECT --to-ports 65534" /etc/firewall.user || echo "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip --dport 80 -j REDIRECT --to-ports 65534" >> /etc/firewall.user
     grep -q "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip --dport 443 -j REDIRECT --to-ports 65535" /etc/firewall.user || echo "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip --dport 443 -j REDIRECT --to-ports 65535" >> /etc/firewall.user
     grep -q "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip -j ACCEPT" /etc/firewall.user || echo "iptables -w -t nat -A prerouting_rule -p tcp -d $pixelservip -j ACCEPT" >> /etc/firewall.user
     grep -q "iptables -w -A forwarding_rule -d $pixelservip -j REJECT" /etc/firewall.user || echo "iptables -w -A forwarding_rule -d $pixelservip -j REJECT" >> /etc/firewall.user
     /etc/init.d/firewall reload >/dev/null  2>&1
+    echo -e -n  '[OK]\n'
 
-    echo 'Setting up AdBlock Config'
+    echo -e -n 'AdBlock config setup... '
     [ -f /etc/config/adblock ] && rm /etc/config/adblock
     touch /etc/config/adblock
     uci set adblock.config='adblock'
@@ -126,6 +130,7 @@ setup()
     uci commit adblock
     grep -q '30 3 1 \* \* /etc/init.d/adblock reload 2>&1 >> /tmp/adblock.log' /etc/crontabs/root || echo '30 3 1 * * /etc/init.d/adblock reload 2>&1 >> /tmp/adblock.log' >> /etc/crontabs/root
     [ ! -f /etc/banner.orig ] && cp /etc/banner /etc/banner.orig && sed -i '$i \[ -f /etc/banner.orig ] && cp /etc/banner.orig /etc/banner' /etc/rc.local
+    echo -e -n  '[OK]\n'
 
     exit 0
 }
@@ -134,7 +139,7 @@ adblock_enabled () {
     local enabled
     config_get_bool enabled 'config' 'enabled' 0
     [ $enabled -gt 0 ] && return 0
-    logger -s -t "adblock[$$]" "adblock is not enabled in the config file"
+    logger -s -t "adblock[$$]" "AdBlock is not enabled in the config file"
     logger -s -t "adblock[$$]" "To enable, run 'uci set adblock.config.enabled=1'"
     return 1
 }
@@ -155,12 +160,12 @@ stop_adblocking () {
 	fi
 	if [ $rst -eq 1 ]; then
 		/etc/init.d/firewall reload >/dev/null  2>&1
-		[ $? -eq 0 ] && output 'Stopped forcing local DNS server.\n' 0 || output 'ERROR: Failed to reload firewall!\n' 0
+		[ $? -eq 0 ] && output 'Not forcing local DNS server.\n' 0 || output 'ERROR: Failed to reload firewall!\n' 0
 	fi
     [ -f /etc/banner.orig ] && cp /etc/banner.orig /etc/banner
     [ -f $hosts_file ] && mv $hosts_file $B_TMP
     /etc/init.d/dnsmasq restart
-	[ $? -eq 0 ] && output "AdBlocking service stopped.\n" 0 || output "ERROR: Failed to restart DNSMASQ!\n" 0
+	[ $? -eq 0 ] && output "AdBlocking stopped.\n" 0 || output "ERROR: Failed to restart DNSMASQ!\n" 0
 }
 
 start_adblocking () {
@@ -169,9 +174,9 @@ start_adblocking () {
     config_get force_dns            'config' 'force_dns' '0'
 
 	if [ -s $B_TMP -a ! "$1" = "reload" ]; then
-		output 'Already downloaded bad hosts file found, reusing it... '
+		output 'Found already downloaded bad hosts file, reusing it... '
 		mv $B_TMP $hosts_file
-	    output 'Done!\n'
+	    output '[OK]\n'
 	else
 		create_bad_hosts_file
 	fi
@@ -235,45 +240,45 @@ create_bad_hosts_file () {
     output 'Downloading bad hosts... '
     output '\n' 2
     for hf in ${bad_hosts}; do
-        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $H_TMP && output 'Done!\n' 2 || output 'FAIL!\n' 2
+        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $H_TMP && output '[OK]\n' 2 || output '[FAIL]\n' 2
     done
-    output 'Done!\n\n'
+    output '[OK]\n\n'
     
     for hf in ${blacklist_domains}; do echo "$hf" >> $D_TMP; done
-    output 'Downloading & processing bad domains... '
+    output 'Downloading bad domains... '
     output '\n' 2
     for hf in ${bad_domains}; do
-        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $D_TMP && output 'Done!\n' 2 || output 'FAIL!\n' 2
+        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $D_TMP && output '[OK]\n' 2 || output '[FAIL]\n' 2
     done
     sed '/^#/!s/^/127.0.0.1 /' $D_TMP >> $H_TMP
-    output 'Done!\n\n'
+    output '[OK]\n\n'
 
-    output 'Downloading whitelisted hosts... '
+    output 'Downloading whitelisted domains... '
     output '\n' 2
     for hf in ${whitelist_urls}; do
-        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $W_TMP && output 'Done!\n' 2 || output 'FAIL!\n' 2
+        output "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $W_TMP && output '[OK]\n' 2 || output '[FAIL]\n' 2
     done
-    output 'Done!\n\n'
+    output '[OK]\n\n'
 
-    output 'Tidying up the hosts file... '
+    output 'Optimizing hosts file... '
     output '\n' 2
-    output 'Cleaning hosts file... ' 2 && sed -i '/localhost/d;s/^0\.0\.0\.0.//;s/^127\.0\.0\.1.//;s/[[:cntrl:]]$//;s/[[:cntrl:]]$/ /;/^#/d;/^$/d;s/[[:space:]]*#.*$//;s/^ //;s/^  //;/^[[:blank:]]*$/d;s|^|'$pixelserv_ip' |' $H_TMP && output 'Done!\n' 2 || output 'FAIL!\n' 2
+    output 'Removing hosts file duplicates... ' 2 && sed -i '/localhost/d;s/^0\.0\.0\.0.//;s/^127\.0\.0\.1.//;s/[[:cntrl:]]$//;s/[[:cntrl:]]$/ /;/^#/d;/^$/d;s/[[:space:]]*#.*$//;s/^ //;s/^  //;/^[[:blank:]]*$/d;s|^|'$pixelserv_ip' |' $H_TMP && output '[OK]\n' 2 || output '[FAIL]\n' 2
     rm -f $hosts_file
-    output 'Sorting hosts file... ' 2 && sort $H_TMP | uniq > $hosts_file  && output 'Done!\n' 2 || output 'FAIL!\n' 2
+    output 'Sorting hosts file... ' 2 && sort $H_TMP | uniq > $hosts_file  && output '[OK]\n' 2 || output '[FAIL]\n' 2
 
-    output 'Excluding whitelisted domains... ' 2
+    output 'Whitelisting domains... ' 2
     whitelist_domains="${whitelist_domains}"$'\n'"$(cat $W_TMP)"
     for hf in ${whitelist_domains}; do 
         expr="$expr/$hf/d;"
     done
-    sed -i "$expr" $hosts_file && output 'Done!\n' 2 || output 'FAIL!\n' 2
-    output 'Done!\n\n'
+    sed -i "$expr" $hosts_file && output '[OK]\n' 2 || output '[FAIL]\n' 2
+    output '[OK]\n\n'
 
-    output 'Cleaning up temp files... '
+    output 'Removing temporary files... '
     rm -f $H_TMP
     rm -f $D_TMP
     rm -f $W_TMP
-    output 'Done!\n\n'
+    output '[OK]\n\n'
 }
 
 reload () {
@@ -318,3 +323,5 @@ stop_service () {
 service_triggers () {
     procd_add_reload_trigger 'adblock'
 }
+
+[ "$1" = "setup" ] && setup
