ufetch-client support implemented

diff --git a/adblock b/adblock
--- a/adblock
+++ b/adblock
@@ -1,5 +1,5 @@
 #!/bin/sh /etc/rc.common
-# adblock init-script utilizing procd version 1.5 by stangri based on bole5's script.
+# adblock init-script utilizing procd version 1.6 by stangri based on bole5's script.
 
 START=99
 USE_PROCD=1
@@ -15,6 +15,8 @@ D_TMP="/tmp/domains.bad.tmp"
 W_TMP="/tmp/hosts.white.tmp"
 DM=/etc/init.d/dnsmasq
 
+[ -s /bin/uclient-fetch ] && CLIENT='/bin/uclient-fetch' || CLIENT='/usr/bin/wget'
+
 debug()
 {
         local level
@@ -23,11 +25,10 @@ debug()
         return 0
 }
 
-
 update()
 {
     echo -e -n 'Updating /etc/init.d/adblock script... '
-    wget --no-check-certificate -qO /etc/init.d/adblock.new https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/adblock && mv /etc/init.d/adblock.new /etc/init.d/adblock && chmod +x /etc/init.d/adblock && echo -e -n  'Done!\n' || echo -e -n 'FAIL!\n' 
+    $CLIENT --no-check-certificate -qO /etc/init.d/adblock.new https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/adblock && mv /etc/init.d/adblock.new /etc/init.d/adblock && chmod +x /etc/init.d/adblock && echo -e -n  'Done!\n' || echo -e -n 'FAIL!\n' 
 }
 
 setup()
@@ -35,24 +36,30 @@ setup()
     local pixelservip=192.168.3.254
     echo 'Setting up Packages'
     opkg update  >/dev/null  2>&1
-    opkg install uhttpd wget coreutils-sort libopenssl >/dev/null  2>&1
+    opkg install uhttpd coreutils-sort >/dev/null 2>&1
+    
+    if [ -s /bin/uclient-fetch ]; then
+    	[ ! -s /lib/libustream-ssl.so ] && opkg install libustream-polarssl >/dev/null 2>&1
+    else
+    	opkg install wget libopenssl >/dev/null  2>&1
+    fi
 
     echo 'Setting up PixelServ'
     if [ ! $(uci -q get uhttpd.pixelserv.listen_http) ]; then
-    mkdir /www_blank
-    echo -ne 'GIF89a1010\x8000\xff\xff\xff000!\xf9\x0400000,000010100\x02\x02D10;' | tr 01 '\000\001' > /www_blank/blank.gif
-    uci add uhttpd uhttpd
-    uci rename uhttpd.@uhttpd[-1]='pixelserv'
-    uci add_list uhttpd.@uhttpd[-1].listen_http='0.0.0.0:81'
-    uci set uhttpd.@uhttpd[-1].home='/www_blank'
-    uci set uhttpd.@uhttpd[-1].rfc1918_filter='1'
-    uci set uhttpd.@uhttpd[-1].max_requests='3'
-    uci set uhttpd.@uhttpd[-1].error_page='/blank.gif'
-    uci set uhttpd.@uhttpd[-1].index_page='blank.gif'
-    uci set uhttpd.@uhttpd[-1].network_timeout='30'
-    uci set uhttpd.@uhttpd[-1].tcp_keepalive='1'
-    uci commit uhttpd
-    /etc/init.d/uhttpd restart
+	    mkdir /www_blank
+	    echo -ne 'GIF89a1010\x8000\xff\xff\xff000!\xf9\x0400000,000010100\x02\x02D10;' | tr 01 '\000\001' > /www_blank/blank.gif
+	    uci add uhttpd uhttpd
+	    uci rename uhttpd.@uhttpd[-1]='pixelserv'
+	    uci add_list uhttpd.@uhttpd[-1].listen_http='0.0.0.0:81'
+	    uci set uhttpd.@uhttpd[-1].home='/www_blank'
+	    uci set uhttpd.@uhttpd[-1].rfc1918_filter='1'
+	    uci set uhttpd.@uhttpd[-1].max_requests='3'
+	    uci set uhttpd.@uhttpd[-1].error_page='/blank.gif'
+	    uci set uhttpd.@uhttpd[-1].index_page='blank.gif'
+	    uci set uhttpd.@uhttpd[-1].network_timeout='30'
+	    uci set uhttpd.@uhttpd[-1].tcp_keepalive='1'
+	    uci commit uhttpd
+	    /etc/init.d/uhttpd restart
     fi
 
     echo 'Setting up Firewall'
@@ -71,20 +78,28 @@ setup()
     uci set adblock.config.hosts_file='/tmp/hosts/hosts.bad'
     uci add_list adblock.config.whitelist_domains='github.com'
     uci add_list adblock.config.whitelist_domains='raw.githubusercontent.com'
-#    uci add_list adblock.config.blacklist_domains='adblocktesting.com'
-    uci add_list adblock.config.bad_hosts='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/hosts.blocked'
-    uci add_list adblock.config.bad_hosts='http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext'
-    uci add_list adblock.config.bad_hosts='http://www.mvps.org/winhelp2002/hosts.txt'
-    uci add_list adblock.config.bad_hosts='http://www.malwaredomainlist.com/hostslist/hosts.txt'
-    uci add_list adblock.config.bad_hosts='http://adaway.org/hosts.txt'
-    uci add_list adblock.config.bad_hosts='http://someonewhocares.org/hosts/hosts'
-    uci add_list adblock.config.bad_hosts='https://zeustracker.abuse.ch/blocklist.php?download=hostfile'
-    uci add_list adblock.config.bad_domains='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/domains.blocked'
-    uci add_list adblock.config.bad_domains='https://palevotracker.abuse.ch/blocklists.php?download=domainblocklist'
-    uci add_list adblock.config.bad_domains='http://mirror1.malwaredomains.com/files/justdomains'
-    uci add_list adblock.config.bad_domains='https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt'
-    uci add_list adblock.config.bad_domains='http://dshield.org/feeds/suspiciousdomains_Low.txt'
-    uci add_list adblock.config.whitelist_urls='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/domains.whitelisted'
+
+#   uci add_list adblock.config.blacklist_domains='adblocktesting.com'
+#	uci add_list adblock.config.bad_hosts='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/hosts.blocked'
+#	uci add_list adblock.config.bad_domains='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/domains.blocked'
+#	uci add_list adblock.config.whitelist_urls='https://raw.githubusercontent.com/stangri/openwrt-simple-adblock/master/domains.whitelisted'
+
+	uci add_list adblock.config.bad_hosts='http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext'	# 63Kb
+	uci add_list adblock.config.bad_hosts='http://www.mvps.org/winhelp2002/hosts.txt'												# 499Kb
+	uci add_list adblock.config.bad_hosts='http://www.malwaredomainlist.com/hostslist/hosts.txt'									# 48Kb
+	uci add_list adblock.config.bad_hosts='http://adaway.org/hosts.txt'																# 13Kb
+	uci add_list adblock.config.bad_hosts='http://someonewhocares.org/hosts/hosts'													# 353Kb
+	uci add_list adblock.config.bad_hosts='https://zeustracker.abuse.ch/blocklist.php?download=hostfile'							# 12Kb
+	uci add_list adblock.config.bad_domains='https://palevotracker.abuse.ch/blocklists.php?download=domainblocklist'				# 1Kb
+	uci add_list adblock.config.bad_domains='http://mirror1.malwaredomains.com/files/justdomains'									# 315Kb
+	uci add_list adblock.config.bad_domains='https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt'					# 93Kb
+	uci add_list adblock.config.bad_domains='http://dshield.org/feeds/suspiciousdomains_High.txt'									# 69Kb
+
+#	uci add_list adblock.config.bad_hosts='http://sysctl.org/cameleon/hosts.win'													# 638Kb
+#	uci add_list adblock.config.bad_hosts='http://hosts-file.net/.\ad_servers.txt'													# 1.7Mb
+#	uci add_list adblock.config.bad_hosts='http://hostsfile.mine.nu/Hosts'															# 2.8Mb
+#	uci add_list adblock.config.bad_hosts='http://support.it-mate.co.uk/downloads/hosts.txt'										# 11.3Mb
+
     uci commit adblock
     
     grep -q '30 3 1 \* \* /etc/init.d/adblock reload 2>&1 >> /tmp/adblock.log' /etc/crontabs/root || echo '30 3 1 * * /etc/init.d/adblock reload 2>&1 >> /tmp/adblock.log' >> /etc/crontabs/root
@@ -130,7 +145,7 @@ create_bad_hosts_file () {
     debug 'Downloading bad hosts... '
     debug '\n' 2
     for hf in ${bad_hosts}; do
-        debug "$hf... " 2 && wget --no-check-certificate -qO- "${hf}" >> $H_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
+        debug "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $H_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
     done
     debug 'Done!\n\n'
     
@@ -138,7 +153,7 @@ create_bad_hosts_file () {
     debug 'Downloading & processing bad domains... '
     debug '\n' 2
     for hf in ${bad_domains}; do
-        debug "$hf... " 2 && wget --no-check-certificate -qO- "${hf}" >> $D_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
+        debug "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $D_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
     done
     sed '/^#/!s/^/127.0.0.1 /' $D_TMP >> $H_TMP
     debug 'Done!\n\n'
@@ -147,7 +162,7 @@ create_bad_hosts_file () {
     debug 'Downloading whitelisted hosts... '
     debug '\n' 2
     for hf in ${whitelist_urls}; do
-        debug "$hf... " 2 && wget --no-check-certificate -qO- "${hf}" >> $W_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
+        debug "$hf... " 2 && $CLIENT --no-check-certificate -qO- "${hf}" >> $W_TMP && debug 'Done!\n' 2 || debug 'FAIL!\n' 2
     done
     debug 'Done!\n\n'
 
@@ -160,7 +175,7 @@ create_bad_hosts_file () {
 
     # Exclude whitelisted domains
     debug 'Excluding whitelisted domains... ' 2
-    whitelist_domains=$whitelist_domains$'\n\r'$(cat $W_TMP)
+    whitelist_domains="${whitelist_domains}\n$(cat $W_TMP)"
     for hf in ${whitelist_domains}; do 
         expr="$expr/$hf/d;"
     done
@@ -175,10 +190,10 @@ create_bad_hosts_file () {
     
 	if [ -s $host_file ]; then
 		debug 'Restarting dnsmasq... ' && $DM restart && debug 'Done!\n'
-		[ $verbosity -eq 0 ] && logger -t 'adblock' "Adblocking service started; blocking $(wc -l < $host_file) domains"
+		[ $verbosity -eq 0 ] && logger -t "adblock[$(pidof adblock)]" "adblocking service started; blocking $(wc -l < $host_file) domains"
 		[ -f /etc/banner.orig ] && cp /etc/banner.orig /etc/banner && sed -i 's/)/ + ADBlock)/' /etc/banner
 	else
-		[ $verbosity -eq 0 ] && logger -t 'adblock' 'Adblocking service failed to start'
+		[ $verbosity -eq 0 ] && logger -t "adblock[$(pidof adblock)]" 'adblocking service failed to start'
 		exit 1
 	fi    
 }
@@ -215,7 +230,7 @@ start_service () {
 stop () {
     config_load adblock
     config_get host_file 'config' 'hosts_file' '/var/hosts/hosts.bad'
-    config_get noise 'config' 'noise' '0'
+    config_get verbosity            'config' 'verbosity' '0'
     [ -f /etc/banner.orig ] && cp /etc/banner.orig /etc/banner
     [ -f $host_file ] && rm -r $host_file && debug 'Restarting dnsmasq... ' && $DM restart && debug 'Done!\n'
 }
@@ -223,7 +238,7 @@ stop () {
 stop_service () {
     config_load adblock
     config_get host_file 'config' 'hosts_file' '/var/hosts/hosts.bad'
-    config_get noise 'config' 'noise' '0'
+    config_get verbosity            'config' 'verbosity' '0'
     [ -f /etc/banner.orig ] && cp /etc/banner.orig /etc/banner
     [ -f $host_file ] && rm -r $host_file && debug 'Restarting dnsmasq... ' && $DM restart && debug 'Done!\n'
 }
